# Generated by Django 5.0.4 on 2024-05-25 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharipovo', '0003_eventtype_event_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
