# Generated by Django 5.0.4 on 2024-05-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharipovo', '0004_remove_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
