# Generated by Django 5.0.4 on 2024-05-26 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharipovo', '0005_remove_ticket_user_ticket_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user_id',
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
