# Generated by Django 5.0.4 on 2024-05-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharipovo', '0006_remove_ticket_user_id_ticket_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
